apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
   name: ts-udp-1
   labels:
     f5cr: "true"
spec:
   virtualServerAddress: "10.0.20.6"
   virtualServerPort: 2123
   mode: standard
   snat: none
   type: udp
   pool:
     service: udp-svc
     servicePort: 2123
       #     monitor:
       #type: udp
       #interval: 10
       #timeout: 31
---
apiVersion: v1
kind: Service
metadata:
  name: udp-svc
  labels:
    app: nginx
spec:
  ports:
  - port: 2123
    protocol: UDP
  selector:
    app: nginx
