apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: lb-policy
  namespace: default
spec:
  snat: none
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    cis.f5.com/ipamLabel: sig
    cis.f5.com/health: '{"interval": 10, "timeout": 31}'
    cis.f5.com/policyName: lb-policy
  labels:
    app: nginx
  name: svc-lb1-udp
  namespace: default
spec:
  externalTrafficPolicy: Local
  healthCheckNodePort: 32151
  type: LoadBalancer
  ports:
    - name: svc-lb1-udp
      port: 2152
      protocol: UDP
      targetPort: 2152
  selector:
    app: nginx
